### ISSUE TITLE
React Group Project

### ISSUE THREAD

**Issue by MostafaShahat2021** [MostafaShahat2021/ReactGroupProject#25]
### In this issue:
- Project Link: 
  - [issue link](https://github.com/MostafaShahat2021/ReactGroupProject/projects/1).
  - [repo link](https://github.com/MostafaShahat2021/ReactGroupProject) 
- We are a group of two coding partners.
We Wish you all the best 😄 .

**Comment by DammyShittu** [comment]
Hi @MostafaShahat2021 and @NalianAchei2020,

## APPROVED 🟢

## Highlights
✔️ Assigned tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MostafaShahat2021** [comment]
Hi @DammyShittu 👋, Thanks a lot for efforts 💯
